import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Bebas_Neue,
  Barlow,
  Fraunces,
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: "600",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aeternus = localFont({
  src: "../public/font/aeternus.ttf",
  variable: "--font-aeternus",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} ${bebasNeue.variable} ${geistSans.variable} ${geistMono.variable} ${fraunces.variable} ${aeternus.variable} h-full antialiased`}
    >
      <GoogleAnalytics gaId="G-8WSBVE4201" />

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
